### ISSUE TITLE
Java sdk has a bug.

### ISSUE THREAD

**Issue by jack20209527** [leap-ai/leap-sdks#7]
the response from your server modelId type is string，bug sdk source code validate as right for json array，so i will not process your example on your readme file example.
<img width="1478" alt="图片" src="https://github.com/leap-ai/leap-sdks/assets/47149104/ae0fdb77-c768-41f6-957c-37f02f2efbef">

please tell me how to solve it.

**Comment by jack20209527** [comment]
I confirm that there is a problem with the data returned by your server, the data returned is as follows:

{"id":"816e1e7a-53e3-4b30-9581-41a29ee24cab","height":1024,"width":1024,"prompt":"8k beautiful girl with headset .","negativePrompt":"asymmetric, watermarks","promptStrength":7,"modelId":"26a1a203-3a46-42cb-8cfa-f4de075907d8","numberOfImages":1,"seed":4523184,"steps":50,"upscalingOption":"x1","createdAt":"2023-09-19T07:36:03.94949+00:00","state":"queued","status":"queued","images":[]}

The returned modelId is of string type, but sdk parses it according to json data, which is what my picture above shows, please change your server, it's been bothering me for a long time!

**Comment by jack20209527** [comment]
hello hello, is anybody here ?

**Comment by eddiechayes** [comment]
Hi @jack20209527, thanks for reporting the issue. I'll investigate this today.

**Comment by jack20209527** [comment]
ok, thanks

**Comment by dphuang2** [comment]
@jack20209527 the latest Java SDK (1.1.4) should solve the issue
